AllCops:
  TargetRubyVersion: 2.4

Metric/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metric/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Enabled: false
